In [11]:
import pandas as pd
import requests

In [12]:
url = 'https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Water_Mains/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson'
response =  requests.get(url)
data = response.json()

# converting the GeoJSON file to a dataframe and then applying the pandas series method to extract the features from 'properties' key
df1 = pd.DataFrame(data['features'])
df1 = df1['properties'].apply(pd.Series)
# saving the dataframe to a csv file with the date it was extracted
df1.to_csv('data/raw/water_main_V1.csv', index=False)

In [13]:
url = 'https://services1.arcgis.com/qAo1OsXi67t7XgmS/arcgis/rest/services/Water_Main_Breaks/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson'
response =  requests.get(url)
data = response.json()

# converting the GeoJSON file to a dataframe and then applying the pandas series method to extract the features from 'properties' key
df2 = pd.DataFrame(data['features'])
df2 = df2['properties'].apply(pd.Series)
# saving the dataframe to a csv file with the date it was extracted
df2.to_csv('data/raw/water_main_break_V1.csv', index=False)

In [14]:
merged_df = pd.merge(df1, df2, on='ROADSEGMENTID', how='left')

In [15]:
merged_df.sample(7)

,OBJECTID_x,WATMAINID,STATUS_x,PRESSURE_ZONE,ROADSEGMENTID,MAP_LABEL,CATEGORY,PIPE_SIZE,MATERIAL,LINED,...,CIVIC_NUMBER,STREET,ASSETID,ASSET_DEPTH,FROST_DEPTH,ASSET_SIZE,ASSET_YEAR_INSTALLED,ASSET_MATERIAL,ASSET_EXISTS,GLOBALID
2389,79970,84570,ACTIVE,KIT 4,10958,6.6m 150mm CI,TREATED,150,CI,NO,...,16,WOODHAVEN RD,43970.0,NaN,NaN,150.0,1957,CI,Y,422b5263-7e0d-46de-8451-c6ef3daf7c70
2223,79809,84424,ACTIVE,KIT 4,12101,9.9m 300mm PVC,TREATED,300,PVC,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1310,78977,34710,ACTIVE,KIT 4,10088,244.3m 300mm DI,TREATED,300,DI,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2444,80008,84612,ACTIVE,KIT 5,600121,3.9m 200mm PVC,TREATED,200,PVC,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1451,79105,59020,ACTIVE,KIT 4,22429,124.1m 150mm PVC,TREATED,150,PVC,NO,...,839,FAIRWAY CRES,83830.0,NaN,NaN,150.0,1995,PVC,Y,65cd8804-b775-4009-8efb-a6b86868d0ba
1813,79417,84142,ACTIVE,KIT 2EA,601515,7.6m 150mm PVC,TREATED,150,PVC,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2425,79994,65900,ACTIVE,KIT 5,40324,39.4m 300mm PVC,TREATED,300,PVC,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
merged_df.shape

(2473, 77)

In [18]:
df1.shape

(2000, 28)

In [19]:
df2.shape

(2000, 50)

The API's seem to only be loading in 2,000 rows for each set of data. Instead of calling the API maybe download the data for each set and then merge them.